---
- name: Reset Target
  hosts: all
  tasks:
    - name: Remove Nginx
      yum:
        name: nginx-1.16.1
        state: absent
        
- name: Reset Local Ansible
  hosts: localhost
  tasks:
    - name: Delete file
      file: 
        path: "{{item}}"
        state: absent
      with_fileglob:
        - "~/*"
        
    - name: Remove wget
      yum:
        name: wget
        state: absent
        
    - name: Remove ansible
      yum:
        name: ansible
        state: absent
