---
- name: Reset Target
  hosts: all
  tasks:
    - name: Remove Nginx
      yum:
        name: nginx-1.16.1
        state: absent

- name: Reset Local Ansible
  hosts: localhost
  tasks:
    - name: Delete file
      file: 
        path: "{{item}}"
        state: absent
      with_items:
        - /home/$(cat /etc/passwd | awk -F ":" '$3 == "1000" {print $1}')/ansible.cfg
        - /home/$(cat /etc/passwd | awk -F ":" '$3 == "1000" {print $1}')/hosts
        - /home/$(cat /etc/passwd | awk -F ":" '$3 == "1000" {print $1}')/index.html
        - /home/$(cat /etc/passwd | awk -F ":" '$3 == "1000" {print $1}')/set_nginx.yml
        - /home/$(cat /etc/passwd | awk -F ":" '$3 == "1000" {print $1}')/reset.yml

    - name: Remove wget
      yum:
        name: wget
        state: absent

    - name: Remove ansible
      yum:
        name: ansible
        state: absent
