---
- name: Setting zabbixserver
  hosts: zab1
  vars:
    ansible_sudo_pass: pass123456789
  tasks:
    - name: Disable SELinux
      selinux:
        state: disabled
      notify: Server Reboot

    - name: Add Repository
      yum:
        name:
          - https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm
          - epel-release
        state: present

    - name: Install Packages
      yum:
        name:
          - zabbix-server-mysql
          - zabbix-web-mysql
          - zabbix-web-japanese
          - zabbix-agent
          - MySQL-python
          - mariadb-server
        state: installed

    - name: Start mariadb
      systemd:
        name: mariadb
        state: started
        enabled: yes

    - name: Create DB
      mysql_db:
        name: zabbix
        collation: utf8_bin
        encoding: utf8
        state: present

    - name: Create DBuser
      mysql_user:
        name: zabbix
        password: pass123456789
        priv: 'zabbix.*:ALL,GRANT'
        state: present

    - name: Check Initial Schema
      shell: mysql -u root -ss zabbix -e "show tables;" | wc -l
      register: show_table_count

    - name: Import Initial Schema
      shell: zcat /usr/share/doc/zabbix-server-mysql*/create.sql.gz | mysql zabbix -u root
      when: show_table_count.stdout == "0"

    - name: Modify zabbix_server.conf
      lineinfile:
        path: '/etc/zabbix/zabbix_server.conf'
        state: present
        owner: root
        group: zabbix
        line: "{{ item }}"
      loop:
        - DBPassword=pass123456789
        - StatsAllowedIP=127.0.0.1

    - name: Setting PHP timezone
      lineinfile:
        path: '/etc/php.ini'
        state: present
        regexp: '^;date.timezone ='
        line: 'date.timezone = "Asia/Tokyo"'

    - name: Japanese localization
      shell: localedef -f UTF-8 -i ja_JP ja_JP

    - name: Restart zabbix
      systemd:
        name: "{{ item }}"
        state: restarted
        enabled: yes
      loop:
        - zabbix-server
        - zabbix-agent
        - httpd

  handlers:
    - name: Server Reboot
      reboot:
        reboot_timeout: 600
